name: nginx-thrift

type: NodePort
ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080

container:
  image: yg397/openresty-thrift
  imageVersion: xenial
  name: nginx-thrift
  ports: 
  - containerPort: 8080
  env:
  - name: fqdn_suffix
    value: ".{{ .Release.Namespace }}.svc.cluster.local"
  volumeMounts:
    - name: lua-scripts
      mountPath: /usr/local/openresty/nginx/lua-scripts
    - name: lua-thrift
      mountPath: /usr/local/openresty/lualib/thrift
    - name: pages
      mountPath: /usr/local/openresty/nginx/pages
    - name: gen-lua
      mountPath: /gen-lua
    - name: keys
      mountPath: /keys
  terminationGracePeriodSeconds: 30
  lifecycle:
    preStop:
      enabled: true
      exec:
        command: ["/bin/sh", "-c", "echo 'shutting_down' > /tmp/nginx_status; sleep 20; /usr/local/openresty/nginx/sbin/nginx -c /etc/nginx/nginx.conf -s quit; while pgrep -x nginx; do sleep 1; done"]


initContainer:
  image: alpine/git
  imageVersion: latest
  name: alpine-container
  volumeMounts:
  - name: lua-scripts
    mountPath: /lua-scripts
  - name: lua-thrift
    mountPath: /lua-thrift
  - name: pages
    mountPath: /pages
  - name: gen-lua
    mountPath: /gen-lua
  - name: keys
    mountPath: /keys
  command: "/bin/sh" 
  args: ["-c", "git clone https://github.com/delimitrou/DeathStarBench.git /DeathStarBench &&
            cp -r /DeathStarBench/socialNetwork/gen-lua/* /gen-lua/ &&
            cp -r /DeathStarBench/socialNetwork/docker/openresty-thrift/lua-thrift/* /lua-thrift/ &&
            cp -r /DeathStarBench/socialNetwork/nginx-web-server/lua-scripts/* /lua-scripts/ &&
            cp -r /DeathStarBench/socialNetwork/nginx-web-server/pages/* /pages/ &&
            cp /DeathStarBench/socialNetwork/keys/* /keys/ "]

volumes:
  - name: lua-scripts
  - name: pages
  - name: gen-lua
  - name: lua-thrift
  - name: keys

configMaps:
  - name: jaeger-config.json
    mountPath: /usr/local/openresty/nginx/jaeger-config.json
    value: jaeger-config

  - name: nginx.conf
    mountPath: /usr/local/openresty/nginx/conf/nginx.conf 
    value: nginx
