name: nginx-thrift

type: NodePort
ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080

terminationGracePeriodSeconds: 600

container:
  image:
    registry: docker.io
    repository: yg397
    name: openresty-thrift
    tag: xenial
  name: nginx-thrift
  ports: 
  - containerPort: 8080
  env:
  - name: fqdn_suffix
    value: ".{{ .Release.Namespace }}.svc.cluster.local"
  volumeMounts:
    - name: lua-scripts
      mountPath: /usr/local/openresty/nginx/lua-scripts
    - name: lua-thrift
      mountPath: /usr/local/openresty/lualib/thrift
    - name: pages
      mountPath: /usr/local/openresty/nginx/pages
    - name: gen-lua
      mountPath: /gen-lua
    - name: keys
      mountPath: /keys
  lifecycle:
    preStop:
      enabled: true
      exec:
        command: 
        - /bin/sh
        - -c
        - |
          echo 'shutting_down' > /tmp/nginx_status
          curl -s http://localhost/nginx-health || true
          # Wait for k8s to redirect traffic (sleep shorter since we're actively rejecting)
          sleep 1
          # Then quit
          nginx -s quit
          # Wait for nginx to exit
          while pgrep -x nginx; do sleep 0.1; done


initContainer:
  image:
    registry: docker.io
    repository: alpine
    name: git
    tag: latest
  name: alpine-container
  volumeMounts:
  - name: lua-scripts
    mountPath: /lua-scripts
  - name: lua-thrift
    mountPath: /lua-thrift
  - name: pages
    mountPath: /pages
  - name: gen-lua
    mountPath: /gen-lua
  - name: keys
    mountPath: /keys
  command: "/bin/sh" 
  args: ["-c", "git clone -b {{ .Values.global.git.branch }} {{ .Values.global.git.repository }} /DeathStarBench &&
            cp -r /DeathStarBench/socialNetwork/gen-lua/* /gen-lua/ &&
            cp -r /DeathStarBench/socialNetwork/docker/openresty-thrift/lua-thrift/* /lua-thrift/ &&
            cp -r /DeathStarBench/socialNetwork/nginx-web-server/lua-scripts/* /lua-scripts/ &&
            cp -r /DeathStarBench/socialNetwork/nginx-web-server/pages/* /pages/ &&
            cp /DeathStarBench/socialNetwork/keys/* /keys/ "]

volumes:
  - name: lua-scripts
  - name: pages
  - name: gen-lua
  - name: lua-thrift
  - name: keys

configMaps:
  - name: jaeger-config.json
    mountPath: /usr/local/openresty/nginx/jaeger-config.json
    value: jaeger-config

  - name: nginx.conf
    mountPath: /usr/local/openresty/nginx/conf/nginx.conf 
    value: nginx