name: search

ports:
  - port: 8082
    targetPort: 8082
 
container:
  command: search
  image: deathstarbench/hotel-reservation
  imageVersion: 0.3.5
  name: hotel-reserv-search
  ports:
  - containerPort: 8082

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config