apiVersion: apps/v1
kind: Deployment
metadata:
  name: idle-deployment-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idle-3
  template:
    metadata:
      labels:
        app: idle-3
    spec:
      nodeSelector:
        kubernetes.io/hostname: node3
      containers:
        - name: stress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: 5
              memory: 640Mi
            requests:
              cpu: 5
              memory: 640Mi