apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-3
  template:
    metadata:
      labels:
        app: stress-3
    spec:
      nodeSelector:
        kubernetes.io/hostname: node3
      containers:
        - name: stress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: 10
              memory: 1280Mi
            requests:
              cpu: 10
              memory: 1280Mi
          args:
            - "--cpu"
            - "8"
            - "--io"
            - "1"
            - "--vm"
            - "1"
            - "--vm-bytes"
            - "1024M"