name: mongodb-reservation

replicas: 1

ports:
  - port: 27022
    targetPort: 27017

container:
  image:
    registry: ~
    repository: mongo
    name: mongo
    tag: 5.0
  name: hotel-reserv-reservation-mongo
  ports:
  - containerPort: 27017