name: memcached-rate

ports:
  - port: 11212
    targetPort: 11211
 
container:
  image:
    registry: ~
    repository: library
    name: memcached
    tag: 1.6.37
  name: hotel-reserv-rate-mmc
  ports:
  - containerPort: 11211