apiVersion: apps/v1
kind: Deployment
metadata:
  name: idle-deployment-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idle-1
  template:
    metadata:
      labels:
        app: idle-1
    spec:
      nodeSelector:
        kubernetes.io/hostname: node1
      containers:
        - name: idle
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "while true; do sleep 30; done;"]
          resources:
            limits:
              cpu: 3
              memory: 384Mi
            requests:
              cpu: 3
              memory: 384Mi