name: rate

ports:
  - port: 8084
    targetPort: 8084
 
container:
  command: rate
  image: deathstarbench/hotel-reservation
  imageVersion: 0.3.5
  name: hotel-reserv-rate
  ports:
  - containerPort: 8084

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config