name: reservation

ports:
  - port: 8087
    targetPort: 8087
 
container:
  command: reservation
  image:
    registry: ~
    repository: ~
    name: ~
    tag: ~
  name: hotel-reserv-reservation
  ports:
  - containerPort: 8087

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config