name: reservation

ports:
  - port: 8087
    targetPort: 8087
 
container:
  command: reservation
  image: deathstarbench/hotel-reservation
  imageVersion: 0.3.5
  name: hotel-reserv-reservation
  ports:
  - containerPort: 8087

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config