name: user-timeline-mongodb

ports:
  - port: 27017
    targetPort: 27017

container:
  args: 
  - --config
  - /social-network-microservices/config/mongod.conf
  readinessProbe:
    exec:
      command:
      - mongo
      - --quiet
      - --eval
      - "db.adminCommand('ping')"
  image:
    registry: docker.io
    repository: library
    name: mongo
    tag: 4.4.6
  name: user-timeline-mongodb
  ports: 
    - containerPort: 27017
  lifecycle:
    preStop:
      enabled: true
      exec:
        command:
        - "/bin/bash"
        - "-c"
        - |
          echo "PRESTOP_HOOK: Starting MongoDB graceful shutdown"
          mongo admin --quiet --eval "db.adminCommand({ shutdown: 1, force: false, timeoutSecs: 10 })" && echo "PRESTOP_HOOK: MongoDB shutdown command completed successfully" || echo "PRESTOP_HOOK: MongoDB shutdown command failed but continuing"
          echo "PRESTOP_HOOK: Finished MongoDB graceful shutdown process"

configMaps:
  - name: mongod.conf
    mountPath: /social-network-microservices/config/mongod.conf
    value: mongod