name: memcached-reserve

ports:
  - port: 11214
    targetPort: 11211
 
container:
  image:
    registry: ~
    repository: library
    name: memcached
    tag: 1.6.37
  name: hotel-reserv-reservation-mmc
  ports:
  - containerPort: 11211