name: memcached-profile

ports:
  - port: 11213
    targetPort: 11211
 
container:
  image:
    registry: ~
    repository: library
    name: memcached
    tag: 1.6.37
  name: hotel-reserv-profile-mmc
  ports:
  - containerPort: 11211