name: post-storage-mongodb

ports:
  - port: 27017
    targetPort: 27017

container:
  args: 
  - --config
  - /social-network-microservices/config/mongod.conf
  readinessProbe:
    exec:
      command:
      - mongo
      - --eval
      - "db.adminCommand('ping')"
  lifecycle:
    preStop:
      enabled: true
      exec:
        command:
        - "/bin/bash"
        - "-c"
        - "mongo admin --eval 'db.shutdownServer()' && sleep 10"
  image:
    registry: docker.io
    repository: library
    name: mongo
    tag: 4.4.6
  name: post-storage-mongodb
  ports: 
  - containerPort: 27017

configMaps:
  - name: mongod.conf
    mountPath: /social-network-microservices/config/mongod.conf
    value: mongod