name: home-timeline-redis

ports:
  - port: 6379
    targetPort: 6379

container:
  args: 
  - /social-network-microservices/config/redis.conf
  image:
    registry: docker.io
    repository: library
    name: redis
    tag: 6.2.4
  name: home-timeline-redis
  ports: 
    - containerPort: 6379

configMaps:
  - name: redis.conf
    mountPath: /social-network-microservices/config/redis.conf
    value: redis