apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-1
  template:
    metadata:
      labels:
        app: stress-1
    nodeSelector:
      kubernetes.io/hostname: node1
    spec:
      containers:
        - name: stress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: 3
              memory: 384Mi
            requests:
              cpu: 3
              memory: 384Mi
          args:
            - "--cpu"
            - "2"
            - "--io"
            - "1"
            - "--vm"
            - "1"
            - "--vm-bytes"
            - "256M"