apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-2
  template:
    metadata:
      labels:
        app: stress-2
    spec:
      nodeSelector:
        kubernetes.io/hostname: node2
      containers:
        - name: stress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          args:
            - "--cpu"
            - "{{ .Values.stress.cpu }}"
            - "--io"
            - "{{ .Values.stress.io }}"
            - "--vm"
            - "{{ .Values.stress.vm }}"
            - "--vm-bytes"
            - "{{ .Values.stress.vmBytes }}"