global:
  nameOverride: ""
  fullnameOverride: ""
  mainChart: hotelres
  replicas: 1
  imagePullPolicy: "IfNotPresent"
  restartPolicy: Always
  serviceType: ClusterIP
  dockerRegistry: docker.io
  defaultImageVersion: latest
  serviceDnsDomain: "cluster.local"
  readinessProbe:
    enabled: true
    initialDelaySeconds: 2
    periodSeconds: 1
    timeoutSeconds: 2
    failureThreshold: 10
    successThreshold: 1
  services:
    environments:
      # TLS enablement
      #  - 0: Disable
      #  - 1: Enabled, using default cipher suite based on golang runtime
      #  - TLS_XXX: Enabled, using the specified Cipher suite, see tls/options.go#L22
      TLS: 0
      LOG_LEVEL: "INFO"
      JAEGER_SAMPLE_RATIO: "1.0"
      MEMC_TIMEOUT: "2"
      GC: "100"
  affinity: {}
  tolerations: []
  nodeSelector: {}
  memcached:
    HACount: 1
    environments:
      MEMCACHED_CACHE_SIZE: "128"
      MEMCACHED_THREADS: "2"
  mongodb:
    persistentVolume:               # use hostPath or pvprovisioner
      enabled: false
      size: "1Gi"
      hostPath:
        enabled: false
        path: /tmp
      pvprovisioner:
        enabled: false
        storageClassName: ceph-fs   # optional