apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment-1
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-1
  template:
    metadata:
      labels:
        app: stress-1
    spec:
      containers:
        - name: stress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--cpu"
            - "100"  # Use a high number to utilize all available CPUs
            - "--io"
            - "1"
            - "--vm"
            - "1"
            - "--vm-bytes"
            - "128M"