name: recommendation

ports:
  - port: 8085
    targetPort: 8085
 
container:
  command: recommendation
  image: deathstarbench/hotel-reservation
  imageVersion: 0.3.5
  name: hotel-reserv-recommendation
  ports:
  - containerPort: 8085

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config