name: consul

replicas: 1

ports:
  - port: 8500
    targetPort: 8500
  - port: 8300
    targetPort: 8300
  - port: 8400
    targetPort: 8400
  - port: 8600
    protocol: UDP
    targetPort: 53

container:
  image: hashicorp/consul
  imageVersion: 1.13.2
  name: consul
  ports:
  - containerPort: 8300
  - containerPort: 8400
  - containerPort: 8500
  - containerPort: 53
    protocol: UDP

nodeSelector:
  kubernetes.io/hostname: node0

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule