name: geo

ports:
  - port: 8083
    targetPort: 8083
 
container:
  command: geo
  image: deathstarbench/hotel-reservation
  imageVersion: 0.3.5
  name: hotel-reserv-geo
  ports:
  - containerPort: 8083

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config