name: mongodb-profile

replicas: 1

ports:
  - port: 27019
    targetPort: 27017
 
container:
  image:
    registry: ~
    repository: jaylenwang
    name: hotel-mongodb
    tag: 5.0-v3
  name: hotel-reserv-profile-mongo
  ports:
  - containerPort: 27017