name: frontend

serviceType: NodePort
ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30050

container:
  command: frontend
  image:
    registry: ~
    repository: ~
    name: ~
    tag: ~
  name: hotel-reserv-frontend
  ports:
  - containerPort: 5000

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config
