name: frontend

serviceType: NodePort
ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30050

container:
  command: frontend
  image: deathstarbench/hotel-reservation
  imageVersion: 0.3.5
  name: hotel-reserv-frontend
  ports:
  - containerPort: 5000

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config
