name: media-frontend

ports:
  - port: 8081
    targetPort: 8080

container:
  image:
    registry: docker.io
    repository: jaylenwang
    name: openresty-thrift
    tag: xenial-v1
  name: media-frontend
  ports: 
  - containerPort: 8081
  env:
  - name: fqdn_suffix
    value: ".{{ .Release.Namespace }}.svc.cluster.local"
  lifecycle:
    preStop:
      enabled: true
      exec:
        command: 
        - /bin/sh
        - -c
        - |
          echo 'shutting_down' > /tmp/nginx_status
          curl -s http://localhost/nginx-health || true
          # Wait for k8s to redirect traffic (sleep shorter since we're actively rejecting)
          sleep 1
          # Then quit
          nginx -s quit
          # Wait for nginx to exit
          while pgrep -x nginx; do sleep 0.1; done

configMaps:
  - name: nginx.conf
    mountPath: /usr/local/openresty/nginx/conf/nginx.conf
    value: nginx

  - name: jaeger-config.yml
    mountPath: /social-network-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config