name: mongodb-geo

replicas: 1

ports:
  - port: 27018
    targetPort: 27017
 
container:
  image:
    registry: ~
    repository: jaylenwang
    name: hotel-mongodb
    tag: 5.0-v2
  name: hotel-reserv-geo-mongo
  ports:
  - containerPort: 27017